version: '3.7'

services:
  server:
    build: .
    ports:
      - "8082:8082"
  postgres:
    container_name: moonpie-postgres
    image: postgres:12.1-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: moonpie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
