
CREATE TABLE IF NOT EXISTS public.color
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT color_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.size
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT size_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.order_table
(
    order_status smallint NOT NULL,
    client_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    comment character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT order_table_pkey PRIMARY KEY (id),
    CONSTRAINT fk45qdixgtn84q8aulwt0xgj81m FOREIGN KEY (client_id)
        REFERENCES public.client (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT order_table_order_status_check CHECK (order_status >= 0 AND order_status <= 2)
);



CREATE TABLE IF NOT EXISTS public.item
(
    price numeric(38,2) NOT NULL,
    quantity_in_stock integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    version bigint,
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    photo_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.item_color
(
    color_id bigint NOT NULL,
    item_id bigint NOT NULL,
    CONSTRAINT item_color_pkey PRIMARY KEY (color_id, item_id),
    CONSTRAINT fkiroblj17dav0yi7vy0jju5cy9 FOREIGN KEY (color_id)
        REFERENCES public.color (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkjo0wxh07jrevjyo39oydtv8w5 FOREIGN KEY (item_id)
        REFERENCES public.item (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.item_size
(
    item_id bigint NOT NULL,
    size_id bigint NOT NULL,
    CONSTRAINT item_size_pkey PRIMARY KEY (item_id, size_id),
    CONSTRAINT fkl2u6gufgvic2q2baxxfxu5gg0 FOREIGN KEY (size_id)
        REFERENCES public.size (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkr7o96qfksgctdy5j228v3fqtg FOREIGN KEY (item_id)
        REFERENCES public.item (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.cart_item
(
    chest integer NOT NULL,
    count integer NOT NULL,
    hip integer NOT NULL,
    price integer NOT NULL,
    waist integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    item_id bigint NOT NULL,
    order_id bigint,
    size_id bigint,
    CONSTRAINT cart_item_pkey PRIMARY KEY (id),
    CONSTRAINT fk23n5618t1gl4kq8d1dxkan27j FOREIGN KEY (order_id)
        REFERENCES public.order_table (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk27btch34nojjlgacglak3yyap FOREIGN KEY (size_id)
        REFERENCES public.size (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdljf497fwm1f8eb1h8t6n50u9 FOREIGN KEY (item_id)
        REFERENCES public.item (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.staff
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT staff_pkey PRIMARY KEY (id)
);
