CREATE TABLE photos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    item_id BIGINT,
    CONSTRAINT photos_pkey PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);
